
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'B390F3856F2080CCDB7E8ECA2F34F884'
    
_lr_action_items = {'FLOAT':([0,9,15,18,],[1,14,21,21,]),'EQUALS':([10,12,],[15,18,]),'VAR':([0,],[2,]),'$end':([3,5,6,14,16,17,19,20,21,22,23,24,25,26,],[-1,0,-2,-4,-3,-7,-5,-6,-13,-8,-11,-12,-9,-10,]),'TEXT':([15,18,],[23,26,]),'INT':([0,11,13,15,18,],[4,16,19,24,24,]),'LET':([0,],[7,]),'ID':([0,1,2,4,7,8,11,13,],[8,9,10,11,12,13,17,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'num':([15,18,],[22,25,]),'declaration':([0,],[3,]),'call':([0,],[5,]),'oper':([0,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> call","S'",1,None,None,None),
  ('call -> declaration','call',1,'p_call','yacc.py',20),
  ('call -> oper','call',1,'p_call','yacc.py',21),
  ('oper -> INT ID INT','oper',3,'p_oper','yacc.py',28),
  ('oper -> FLOAT ID FLOAT','oper',3,'p_oper','yacc.py',29),
  ('oper -> ID ID INT','oper',3,'p_oper','yacc.py',30),
  ('oper -> ID ID ID','oper',3,'p_oper','yacc.py',31),
  ('oper -> INT ID ID','oper',3,'p_oper','yacc.py',32),
  ('declaration -> VAR ID EQUALS num','declaration',4,'p_declaration','yacc.py',36),
  ('declaration -> LET ID EQUALS num','declaration',4,'p_declaration','yacc.py',37),
  ('declaration -> LET ID EQUALS TEXT','declaration',4,'p_declaration','yacc.py',38),
  ('declaration -> VAR ID EQUALS TEXT','declaration',4,'p_declaration','yacc.py',39),
  ('num -> INT','num',1,'p_num','yacc.py',50),
  ('num -> FLOAT','num',1,'p_num','yacc.py',51),
]
